using System.Collections.Generic;
using UnityEngine;

public class ShotVariables : MonoBehaviour
{
	public static Dictionary<string, float> optimalShotTable;

	public static void InitShotVariables()
	{
		optimalShotTable = new Dictionary<string, float>();
		optimalShotTable.Add("squareDriveOptimalShotLength", 17.5f);
		optimalShotTable.Add("squareDriveOptimalShotFrame", 6f);
		optimalShotTable.Add("bt6PullShotOptimalShotLength", 18.4f);
		optimalShotTable.Add("bt6PullShotOptimalShotFrame", 7f);
		optimalShotTable.Add("bt6LateCutOptimalShotLength", 17.5f);
		optimalShotTable.Add("bt6LateCutOptimalShotFrame", 19f);
		optimalShotTable.Add("bt6SquareCutOptimalShotLength", 17.4f);
		optimalShotTable.Add("bt6SquareCutOptimalShotFrame", 10f);
		optimalShotTable.Add("bt6StraightDriveOptimalShotLength", 15.7f);
		optimalShotTable.Add("bt6StraightDriveOptimalShotFrame", 10f);
		optimalShotTable.Add("bt6ReverseSweepOptimalShotLength", 15.5f);
		optimalShotTable.Add("bt6ReverseSweepOptimalShotFrame", 14f);
		optimalShotTable.Add("bt6CoverDriveOptimalShotLength", 17f);
		optimalShotTable.Add("bt6CoverDriveOptimalShotFrame", 15f);
		optimalShotTable.Add("bt6DefenseOptimalShotLength", 15.8f);
		optimalShotTable.Add("bt6DefenseOptimalShotFrame", 12f);
		optimalShotTable.Add("bt6HookShotOptimalShotLength", 16.4f);
		optimalShotTable.Add("bt6HookShotOptimalShotFrame", 10f);
		optimalShotTable.Add("bt6LegGlanceOptimalShotLength", 15.8f);
		optimalShotTable.Add("bt6LegGlanceOptimalShotFrame", 14f);
		optimalShotTable.Add("bt6OffDriveOptimalShotLength", 17.4f);
		optimalShotTable.Add("bt6OffDriveOptimalShotFrame", 16f);
		optimalShotTable.Add("bt6OnDriveOptimalShotLength", 15.5f);
		optimalShotTable.Add("bt6OnDriveOptimalShotFrame", 16f);
		optimalShotTable.Add("loftOffSideOptimalShotLength", 16.2f);
		optimalShotTable.Add("loftOffSideOptimalShotFrame", 15f);
		optimalShotTable.Add("loftLegSideOptimalShotLength", 16.2f);
		optimalShotTable.Add("loftLegSideOptimalShotFrame", 16f);
		optimalShotTable.Add("loftStraightOptimalShotLength", 16f);
		optimalShotTable.Add("loftStraightOptimalShotFrame", 16f);
		optimalShotTable.Add("insideOutCoverDriveOptimalShotLength", 16.7f);
		optimalShotTable.Add("insideOutCoverDriveOptimalShotFrame", 11f);
		optimalShotTable.Add("lateSquareDriveOptimalShotLength", 17.3f);
		optimalShotTable.Add("lateSquareDriveOptimalShotFrame", 8f);
		optimalShotTable.Add("legGlanceYorkerLengthOptimalShotLength", 17.5f);
		optimalShotTable.Add("legGlanceYorkerLengthOptimalShotFrame", 10f);
		optimalShotTable.Add("backFootStraightDriveOptimalShotLength", 17.6f);
		optimalShotTable.Add("backFootStraightDriveOptimalShotFrame", 17f);
		optimalShotTable.Add("backFootDefenseHighBallOptimalShotLength", 17.6f);
		optimalShotTable.Add("backFootDefenseHighBallOptimalShotFrame", 17f);
		optimalShotTable.Add("frontFootOffSideDefenseOptimalShotLength", 15.8f);
		optimalShotTable.Add("frontFootOffSideDefenseOptimalShotFrame", 11f);
		optimalShotTable.Add("extraCoverDriveOptimalShotLength", 15.3f);
		optimalShotTable.Add("extraCoverDriveOptimalShotFrame", 14f);
		optimalShotTable.Add("lateCutLowHeightOptimalShotLength", 17.75f);
		optimalShotTable.Add("lateCutLowHeightOptimalShotFrame", 16f);
		optimalShotTable.Add("backFootOffDriveOptimalShotLength", 17.5f);
		optimalShotTable.Add("backFootOffDriveOptimalShotFrame", 14f);
		optimalShotTable.Add("backFootOnDriveOptimalShotLength", 18.5f);
		optimalShotTable.Add("backFootOnDriveOptimalShotFrame", 14f);
		optimalShotTable.Add("paddleSweepOptimalShotLength", 15.8f);
		optimalShotTable.Add("paddleSweepOptimalShotFrame", 12f);
		optimalShotTable.Add("lowPullShotOptimalShotLength", 17.4f);
		optimalShotTable.Add("lowPullShotOptimalShotFrame", 18f);
		optimalShotTable.Add("lowPullShot1OptimalShotLength", 17.2f);
		optimalShotTable.Add("lowPullShot1OptimalShotFrame", 18f);
		optimalShotTable.Add("straightDrivePowerShotOptimalShotLength", 16.5f);
		optimalShotTable.Add("straightDrivePowerShotOptimalShotFrame", 13f);
		optimalShotTable.Add("powerfulSweepShotOptimalShotLength", 17.5f);
		optimalShotTable.Add("powerfulSweepShotOptimalShotFrame", 16f);
		optimalShotTable.Add("frontFootOffDriveOptimalShotLength", 15.5f);
		optimalShotTable.Add("frontFootOffDriveOptimalShotFrame", 15f);
        optimalShotTable.Add("frontFootOffDriveShotLength", 15.5f);
        optimalShotTable.Add("frontFootOffDriveShotFrame", 15f);
        optimalShotTable.Add("WCCLite_ABdeVilliers_ShotOptimalShotLength", 15.75f);
		optimalShotTable.Add("WCCLite_ABdeVilliers_ShotOptimalShotFrame", 17f);
		optimalShotTable.Add("WCCLite_BackFootPunchOptimalShotLength", 17.4f);
		optimalShotTable.Add("WCCLite_BackFootPunchOptimalShotFrame", 14f);
		optimalShotTable.Add("WCCLite_HarbhajanShotOptimalShotLength", 17.2f);
		optimalShotTable.Add("WCCLite_HarbhajanShotOptimalShotFrame", 32f);
		optimalShotTable.Add("WCCLite_HelicopterShotOptimalShotLength", 17f);
		optimalShotTable.Add("WCCLite_HelicopterShotOptimalShotFrame", 19f);
		optimalShotTable.Add("WCCLite_LegGlanceNewOptimalShotLength", 18.5f);
		optimalShotTable.Add("WCCLite_LegGlanceNewOptimalShotFrame", 17.5f);
		optimalShotTable.Add("WCCLite_LoftedSquareDriveOptimalShotLength", 17.2f);
		optimalShotTable.Add("WCCLite_LoftedSquareDriveOptimalShotFrame", 14f);
		optimalShotTable.Add("WCCLite_YorkerLegGlanceNewOptimalShotLength", 20f);
		optimalShotTable.Add("WCCLite_YorkerLegGlanceNewOptimalShotFrame", 19f);
		optimalShotTable.Add("WCCLite_DilscoopOptimalShotLength", 16.25f);
		optimalShotTable.Add("WCCLite_DilscoopOptimalShotFrame", 21f);
		optimalShotTable.Add("WCCLite_LoftedReverseSweepOptimalShotLength", 16f);
		optimalShotTable.Add("WCCLite_LoftedReverseSweepOptimalShotFrame", 34f);
		optimalShotTable.Add("runDownOnDriveOptimalShotLength", 17.5f);
		optimalShotTable.Add("runDownOnDriveOptimalShotFrame", 16f);
		optimalShotTable.Add("lowHookShotOptimalShotLength", 16.85f);
		optimalShotTable.Add("lowHookShotOptimalShotFrame", 19f);
		optimalShotTable.Add("loftStraightShortBallOptimalShotLength", 16.75f);
		optimalShotTable.Add("loftStraightShortBallOptimalShotFrame", 10f);
		optimalShotTable.Add("reverseSweepSlowBallOptimalShotLength", 16.2f);
		optimalShotTable.Add("reverseSweepSlowBallOptimalShotFrame", 14f);
		optimalShotTable.Add("bt6SweepOptimalShotLength", 16.2f);
		optimalShotTable.Add("bt6SweepOptimalShotFrame", 13f);
	}
}
